# Generated by Django 4.0.3 on 2022-03-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='links',
            new_name='link',
        ),
    ]
